import Head from 'next/head'
import Hero from '@/components/Hero'
import Features from '@/components/Features'
import Testimonials from '@/components/Testimonials'
import Contact from '@/components/Contact'
import AOS from 'aos';
import 'aos/dist/aos.css'; // You can also use <link> for styles
import { useEffect } from 'react'
export default function Home() {
  useEffect(() => {
    AOS.init({duration:1000});
  }, [])
  return (
    <div style={{overflowX:"hidden"}}>
      <Head>
        <title>MarkAll</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      </Head>

      <Hero />

      <Features />

      <div style={{
        margin: "100px 0px",
      }}>
        <Testimonials />
      </div>

      <div style={{
        margin: "100px 0px",
      }}>
        <Contact />
      </div>
    </div>
  )
}
